#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Production secrets live in .env.production, kept completely separate from
# the local-dev .env (so local dev can never accidentally point at prod).
ENV_FILE=".env.production"
SERVICE_NAME="betti-coaching-calendar"

TOTAL_STAGES=8

banner "betti-coaching-calendar: Neon + Cloud Run production setup"

# ── Stage 1: gcloud CLI ─────────────────────────────────────────────────────
stage "Google Cloud CLI"
say "We need the gcloud CLI installed and logged in before anything else."

# Common Windows install location, in case this shell's PATH predates the
# installer (e.g. an already-open terminal/IDE that started before install).
_GCLOUD_DEFAULT_BIN="/c/Users/$(whoami 2>/dev/null || echo "$USER")/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin"
if ! command -v gcloud >/dev/null 2>&1 && [[ -x "$_GCLOUD_DEFAULT_BIN/gcloud" ]]; then
  export PATH="$PATH:$_GCLOUD_DEFAULT_BIN"
  note "gcloud wasn't on PATH yet in this shell; added $_GCLOUD_DEFAULT_BIN for this run."
  note "Restart your terminal (or Claude Code) once so this is permanent."
fi

# On Windows, gcloud needs a real Python - Windows' "python" App Execution
# Alias stub (the Microsoft Store prompt) isn't one. Point it at the Python
# the Cloud SDK installer bundled, if present, to sidestep that entirely.
_GCLOUD_BUNDLED_PYTHON="/c/Users/$(whoami 2>/dev/null || echo "$USER")/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/bundledpython/python.exe"
if [[ -z "${CLOUDSDK_PYTHON:-}" && -x "$_GCLOUD_BUNDLED_PYTHON" ]]; then
  export CLOUDSDK_PYTHON="$_GCLOUD_BUNDLED_PYTHON"
fi

if command -v gcloud >/dev/null 2>&1; then
  say "Found gcloud: $(gcloud --version | head -n1)"
else
  warn "gcloud CLI not found."
  step "Install it from the official installer, then re-run this script."
  open_url "https://cloud.google.com/sdk/docs/install#windows"
  say "On Windows: download and run GoogleCloudSDKInstaller.exe, follow the prompts,"
  say "then open a NEW terminal (so PATH updates) and re-run this script."
  exit 1
fi
if ! gcloud auth print-access-token >/dev/null 2>&1; then
  step "Logging you in - a browser window will open."
  gcloud auth login
fi
say "Logged in as: $(gcloud config get-value account 2>/dev/null)"

# ── Stage 2: GCP project + billing ──────────────────────────────────────────
stage "Google Cloud project & billing"
say "Pick (or create) the project this app will live in."
open_url "https://console.cloud.google.com/projectselector2/home/dashboard"
step "Create a project (or pick an existing one) and copy its Project ID"
step "(not the display name - the short lowercase-with-dashes ID)."
ask GCP_PROJECT_ID "Project ID:"
gcloud config set project "$GCP_PROJECT_ID"
say ""
warn "Cloud Run needs a billing account linked to run past the free trial."
say "This will NOT auto-charge you: Cloud Run's Always Free tier (2M requests/"
say "month) keeps working at \$0 after you link a card, way above what a"
say "low-traffic booking site will ever use."
open_url "https://console.cloud.google.com/billing/linkedaccount?project=$GCP_PROJECT_ID"
step "Link (or create) a billing account for this project."
say "Optional but recommended: set a small budget alert (e.g. \$1) as a safety net:"
open_url "https://console.cloud.google.com/billing/budgets?project=$GCP_PROJECT_ID"
confirm "Billing account linked to $GCP_PROJECT_ID?" || { warn "Come back once it's linked - Cloud Run deploy will fail without it."; exit 1; }
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"

# ── Stage 3: Enable required APIs ───────────────────────────────────────────
stage "Enable required APIs"
say "Enabling Cloud Run, Cloud Build, Artifact Registry, and the Google"
say "Calendar API (needed later for the Meet-link integration)."
gcloud services enable \
  run.googleapis.com \
  cloudbuild.googleapis.com \
  artifactregistry.googleapis.com \
  calendar-json.googleapis.com \
  --project "$GCP_PROJECT_ID"
say "Done."

# ── Stage 4: Neon Postgres ──────────────────────────────────────────────────
stage "Neon: database"
say "Create a free Postgres database - this becomes DATABASE_URL."
open_url "https://console.neon.tech"
step "Sign up / log in, create a project, then open the Connection Details panel."
step "Switch it to the 'Direct connection' (not 'Pooled connection')."
note "Direct, not pooled: at this app's low traffic there's no need for PgBouncer,"
note "and it sidesteps a known Prisma-migrations-through-PgBouncer quirk."
step "Copy the full connection string (starts postgresql://...)."
ask_secret DATABASE_URL "Paste the Neon direct connection string:"
write_env DATABASE_URL "$DATABASE_URL"

# ── Stage 5: Google OAuth client (for the Meet-link integration) ───────────
stage "Google OAuth client (Meet-link integration)"
say "This is the OAuth client the app uses to mint fresh Google Meet links."
say "We don't know the Cloud Run URL yet, so we'll use a placeholder redirect"
say "URI now and fix it in Stage 7 once the service is live."
open_url "https://console.cloud.google.com/apis/credentials?project=$GCP_PROJECT_ID"
step "Create Credentials -> OAuth client ID -> Application type: Web application."
step "Under Authorized redirect URIs, add: http://localhost:3000/admin/google/callback"
note "(placeholder for now; you'll add the real Cloud Run one in Stage 7)"
step "Also open the OAuth consent screen and set Publishing status to 'In production'"
step "(not 'Testing') - otherwise Google expires the refresh token after 7 days."
open_url "https://console.cloud.google.com/apis/credentials/consent?project=$GCP_PROJECT_ID"
step "Back on the credentials page, copy the Client ID and Client secret."
ask GOOGLE_CLIENT_ID "Google OAuth Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Google OAuth Client secret:"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
write_env GOOGLE_OAUTH_REDIRECT_URI "http://localhost:3000/admin/google/callback"

# ── Stage 6: remaining app config ───────────────────────────────────────────
stage "Remaining app configuration"
say "A few more values - see .env.example in the repo for context on each."
ask BUSINESS_TIMEZONE "Business timezone [Europe/Budapest]:"
BUSINESS_TIMEZONE="${BUSINESS_TIMEZONE:-Europe/Budapest}"
ask FRONTEND_URL "Frontend URL (CORS origin - a placeholder is fine for now) [http://localhost:5173]:"
FRONTEND_URL="${FRONTEND_URL:-http://localhost:5173}"
note "You'll come back and update this once the frontend has a real domain."
say ""
say "Email sending, via Gmail's own SMTP (an App Password, not your account"
say "password - this only works if the From address is that same Gmail"
say "account, or a 'Send mail as' alias configured on it)."
step "Turn on 2-Step Verification first if it isn't already on, then generate"
step "an App Password:"
open_url "https://myaccount.google.com/apppasswords"
ask GMAIL_USER "Gmail address (e.g. you@gmail.com):"
ask_secret GMAIL_APP_PASSWORD "App Password (16 characters, no spaces):"
ask EMAIL_FROM "EMAIL_FROM (e.g. 'Betti Coaching <$GMAIL_USER>'):"
say ""
say "Generating JWT_SECRET and ENCRYPTION_KEY locally - no dashboard needed"
say "for these, the app signs its own login tokens and doesn't use Frontegg."
if [[ -z "$(_existing JWT_SECRET || true)" ]]; then
  JWT_SECRET=$(openssl rand -base64 48)
else
  JWT_SECRET=$(_existing JWT_SECRET)
  note "reusing existing JWT_SECRET from $ENV_FILE"
fi
if [[ -z "$(_existing ENCRYPTION_KEY || true)" ]]; then
  ENCRYPTION_KEY=$(openssl rand -base64 32)
else
  ENCRYPTION_KEY=$(_existing ENCRYPTION_KEY)
  note "reusing existing ENCRYPTION_KEY from $ENV_FILE"
fi
write_env BUSINESS_TIMEZONE "$BUSINESS_TIMEZONE"
write_env FRONTEND_URL "$FRONTEND_URL"
write_env GMAIL_USER "$GMAIL_USER"
write_env GMAIL_APP_PASSWORD "$GMAIL_APP_PASSWORD"
write_env EMAIL_FROM "$EMAIL_FROM"
write_env JWT_SECRET "$JWT_SECRET"
write_env ENCRYPTION_KEY "$ENCRYPTION_KEY"

# ── Stage 7: build env.yaml and deploy ──────────────────────────────────────
stage "Deploy to Cloud Run"
say "Writing env.yaml (gitignored) for Cloud Run from the values above,"
say "then deploying. Cloud Build builds the existing Dockerfile remotely -"
say "no local Docker needed for this part."
cat > env.yaml <<YAML
DATABASE_URL: "$(_existing DATABASE_URL)"
BUSINESS_TIMEZONE: "$(_existing BUSINESS_TIMEZONE)"
FRONTEND_URL: "$(_existing FRONTEND_URL)"
JWT_SECRET: "$(_existing JWT_SECRET)"
GMAIL_USER: "$(_existing GMAIL_USER)"
GMAIL_APP_PASSWORD: "$(_existing GMAIL_APP_PASSWORD)"
EMAIL_FROM: "$(_existing EMAIL_FROM)"
GOOGLE_CLIENT_ID: "$(_existing GOOGLE_CLIENT_ID)"
GOOGLE_CLIENT_SECRET: "$(_existing GOOGLE_CLIENT_SECRET)"
GOOGLE_OAUTH_REDIRECT_URI: "$(_existing GOOGLE_OAUTH_REDIRECT_URI)"
ENCRYPTION_KEY: "$(_existing ENCRYPTION_KEY)"
YAML
say "Wrote env.yaml"
note "Not committed - it holds real secrets (also true of $ENV_FILE)."
say ""
ask GCP_REGION "Cloud Run region [europe-west1]:"
GCP_REGION="${GCP_REGION:-europe-west1}"
write_env GCP_REGION "$GCP_REGION"
say ""
step "Deploying (this uploads the source and builds it in the cloud - a few minutes)."
if ! gcloud run deploy "$SERVICE_NAME" \
  --source . \
  --region "$GCP_REGION" \
  --project "$GCP_PROJECT_ID" \
  --allow-unauthenticated \
  --env-vars-file env.yaml; then
  warn "Deploy failed - check the error above (common causes: billing not"
  warn "linked yet, or an API not enabled). Fix it and re-run this script;"
  warn "it remembers everything you've already entered."
  exit 1
fi
say "Deployed."

# ── Stage 8: post-deploy wiring ─────────────────────────────────────────────
stage "Post-deploy wiring"
SERVICE_URL=$(gcloud run services describe "$SERVICE_NAME" --region "$GCP_REGION" --project "$GCP_PROJECT_ID" --format 'value(status.url)')
say "Live at: $SERVICE_URL"
step "Health check:"
if command -v curl >/dev/null 2>&1; then
  curl -s "$SERVICE_URL/health" && printf '\n' || warn "health check didn't respond - give it a few seconds and retry manually."
fi
say ""
say "Now point the Meet-link OAuth redirect at the real URL instead of the"
say "localhost placeholder from Stage 5:"
REAL_REDIRECT_URI="$SERVICE_URL/admin/google/callback"
say "  $REAL_REDIRECT_URI"
open_url "https://console.cloud.google.com/apis/credentials?project=$GCP_PROJECT_ID"
step "Open your OAuth client, add the URI above to Authorized redirect URIs, Save."
write_env GOOGLE_OAUTH_REDIRECT_URI "$REAL_REDIRECT_URI"
step "Updating the Cloud Run service's env var to match..."
gcloud run services update "$SERVICE_NAME" \
  --region "$GCP_REGION" \
  --project "$GCP_PROJECT_ID" \
  --update-env-vars "GOOGLE_OAUTH_REDIRECT_URI=$REAL_REDIRECT_URI" >/dev/null
say "Done."
say ""
warn "One thing left that this script deliberately does NOT do for you:"
say "create the admin account. Run this once, locally, against the production"
say "database (so the password is only ever typed on your machine, never"
say "stored in env.yaml or Cloud Run's config):"
say ""
say "  DATABASE_URL=\"$(_existing DATABASE_URL)\" node scripts/seed-admin.mjs"
say ""
step "Run that now in another terminal, then come back here and press Enter."
pause
say ""
note "Once your frontend has a real domain, come back and run:"
note "  gcloud run services update $SERVICE_NAME --region $GCP_REGION --project $GCP_PROJECT_ID --update-env-vars FRONTEND_URL=https://your-frontend-domain"
note "Then, as the admin you just seeded, log in via POST $SERVICE_URL/auth/login"
note "and visit $SERVICE_URL/admin/google/connect once to finish the"
note "one-time Google Calendar connection (see README)."

finish
say "Service URL: $SERVICE_URL"
